name:           TastyTLT
version:        0.0.0.0
github:         "jphmrst/TLT-Tasty"
license:        LGPL-3
author:         "John Maraist"
maintainer:     "haskell-tlt@maraist.org"
copyright:      "2022 John Maraist"
category:       Test
synopsis:       "Run TLT tests from Tasty"
description:    "TLT is a quick-and-dirty unit test system without test specifications, motivated by easy examination of intermediate results of computations in monad transformers.  See the GitHub repository <https://github.com/jphmrst/TLT/> for documentation, or the Haddock page for additional examples."

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base          (>= 4.14.1 && < 4.15) || (>= 4.15.1 && < 4.16) || (>= 4.16.0 && < 4.17)
- transformers  >= 0.5.6  && < 0.6
- ansi-terminal >= 0.11.1 && < 0.12
- STMonadTrans  >= 0.4.6  && < 0.5
- resourcet     >= 1.2.4  && < 1.3
- free          >= 5.1.7  && < 5.2
- mtl           >= 2.2.2  && < 2.3
- TLT           >= 0.3.0  && < 0.4
- tasty         >= 1.4.2  && < 1.5
- tagged        >= 0.8.6  && < 0.8.7

library:
  source-dirs: src

executables:
  TLT-exe:
    main:                Failing.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TLT
    - TastyTLT

tests:
  TLT-test-fail:
    main:                Passing.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TLT
    - TastyTLT
